import { describe, expect, it } from 'vitest';

import {
  BodyWeightEntry,
  DomainError,
  DomainId,
  Duration,
  ExerciseDefinition,
  Energy,
  GoalConfiguration,
  HydrationEntry,
  HydrationTarget,
  Length,
  Mass,
  NutritionFacts,
  UserProfile,
  Volume,
  activityMultipliers,
  bmiCategories,
  calculateAge,
  calculateBmi,
  calculateDailyCalorieTarget,
  err,
  estimateMaintenanceEnergy,
  estimateRestingEnergy,
  exerciseEquipment,
  exerciseLoggingModes,
  exerciseMuscleGroups,
  goalTypes,
  isErr,
  isOk,
  nutritionProvenances,
  ok,
  scaleNutritionFacts,
  summarizeHydrationEntries,
} from './index';

describe('@fitness/domain public API', () => {
  it('exports every approved runtime concept', () => {
    expect([
      BodyWeightEntry,
      DomainError,
      DomainId,
      Duration,
      ExerciseDefinition,
      Energy,
      GoalConfiguration,
      HydrationEntry,
      HydrationTarget,
      Length,
      Mass,
      NutritionFacts,
      UserProfile,
      Volume,
      activityMultipliers,
      bmiCategories,
      calculateAge,
      calculateBmi,
      calculateDailyCalorieTarget,
      err,
      estimateMaintenanceEnergy,
      estimateRestingEnergy,
      exerciseEquipment,
      exerciseLoggingModes,
      exerciseMuscleGroups,
      goalTypes,
      isErr,
      isOk,
      nutritionProvenances,
      ok,
      scaleNutritionFacts,
      summarizeHydrationEntries,
    ]).not.toContain(undefined);
  });
});
