import type { StarterExercise } from './starter-exercises';

/**
 * A larger, opt-in Exercise Definition pack a person may add on top of an
 * empty library or the starter set, in one deliberate act, exactly as
 * Specification 0027 established for the starter exercises this reuses the
 * shape and the mechanism of.
 *
 * Sourced and curated from the MIT-licensed hasaneyldrm/exercises-dataset
 * (github.com/hasaneyldrm/exercises-dataset, commit
 * 7455efae41b330c265e7cd4b78dfa848e7ce5eb, retrieved 2026-08-24). Only the
 * English exercise name, equipment, and target-muscle classification were
 * used — never the multilingual instruction text or any image or GIF,
 * which that dataset separately attributes to Gym visual and does not
 * license for reuse. Every entry was mechanically re-mapped onto this
 * catalog’s existing controlled vocabulary and filtered for unambiguous,
 * neutral naming; nothing here widens the schema the starter set already
 * established.
 *
 * Identifiers are UUID version 5 literals, generated offline the same way
 * the starter set’s are: the namespace
 * `6ba7b812-9dad-11d1-80b4-00c04fd430c8` plus the entry’s normalized name.
 * Disjoint from the starter set and from any person-created definition by
 * construction, and verified disjoint from both by the accompanying tests.
 *
 * No entry carries notes, for the same reason the starter set carries none:
 * a note is where technique or coaching guidance would creep in, and none is
 * favorited, because a favorite is the person’s own statement.
 */
export const expandedExercises: readonly StarterExercise[] = Object.freeze([
  {
    equipment: 'barbell',
    id: '6a1e22ff-de31-50a3-aeb1-5b17b9fd8645',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Incline Row',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'barbell',
    id: '0c66a277-f759-5496-a5f8-6a8404fe0ed3',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Pullover',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'barbell',
    id: 'f3b8c5ac-89f1-5dc8-b40f-bc3840d88935',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'barbell',
    id: 'b8bfd78c-24b3-5fc0-8990-7aedc1ceb306',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'barbell',
    id: '13796bd7-d81f-506a-aacf-3170c52355e6',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Drag Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'barbell',
    id: '2bfe48aa-f0fd-519b-94d0-332f61e9116f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Preacher Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'barbell',
    id: 'af335a64-1931-5b93-9e6a-32bf47500455',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Floor Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'barbell',
    id: 'a94366bb-eb20-5270-9367-05b14be17059',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Seated Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'barbell',
    id: '58433bf6-5b6a-5af3-8be9-d1ef48a3385d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Decline Bench Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'barbell',
    id: '4ec8efff-f8e9-512d-a144-194a24a8c6e4',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Decline Pullover',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'barbell',
    id: '068a02dd-1c14-53a3-a865-6028d0a62c90',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Rollout',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'barbell',
    id: '7c6d8f44-810c-5b2b-a0f0-3c13da906f7f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Landmine 180',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'barbell',
    id: 'bce2f105-848b-500f-a092-0eae46d8c9ec',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Lunge',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'barbell',
    id: '6e6dd7b5-01cc-5312-b746-e1d0b0a8d372',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Step-up',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'barbell',
    id: 'b3e97268-79a3-5e44-960b-ea657d9c27e2',
    loggingMode: 'external-load-and-repetitions',
    name: 'Frankenstein Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'barbell',
    id: 'dfb46f13-d872-5c19-a929-17190abf3621',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Good Morning',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'barbell',
    id: '4dfaee9b-bb75-57b6-bb6e-81a8ac23ee6e',
    loggingMode: 'external-load-and-repetitions',
    name: 'Power Clean',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'barbell',
    id: '447a33df-bc86-5a75-a223-684e71b0feba',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Bench Squat',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'barbell',
    id: '2ab8d67f-3cd4-55a0-b40f-1cdc05437f71',
    loggingMode: 'external-load-and-repetitions',
    name: 'Snatch Pull',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'barbell',
    id: 'caeebda6-8821-5f49-b65a-02cd948f16cd',
    loggingMode: 'external-load-and-repetitions',
    name: 'Squat Jerk',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'barbell',
    id: '8a71ed6f-650f-51f0-9cf8-be1a0f3d3d1d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Skier',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'barbell',
    id: '0267fc55-b544-5e90-adb5-72e18d11f369',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Thruster',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'barbell',
    id: 'a804bb76-d791-56ff-a794-82c8e93bbe15',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Close-grip Bench Press',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'barbell',
    id: '00783092-fe0d-5486-aa14-1888ade7ff24',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Lying Extension',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'barbell',
    id: '79b6770c-72b6-523e-bed8-95a9e2cbc641',
    loggingMode: 'external-load-and-repetitions',
    name: 'Barbell Pin Presses',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'bodyweight',
    id: 'b9773fa2-5d8f-56b4-8047-8cf76d0e41c0',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Hyperextension',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'bodyweight',
    id: '5d5676ba-9935-5285-912f-7a37881794b5',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'L-pull-up',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'bodyweight',
    id: 'a18a3f92-9e71-57f7-8782-d19b7a62feb3',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Muscle Up',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'bodyweight',
    id: '3e95510b-98cc-5369-b6d6-1f591384df9d',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted One Hand Pull Up',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'bodyweight',
    id: '32cf0d43-cb6c-5f00-a79c-57662abd0b11',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Biceps Pull-up',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'bodyweight',
    id: '1312ec42-269e-5601-8222-15853e0291f8',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Standing Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'bodyweight',
    id: '437a2110-3aba-546e-9964-7eeea9f23d66',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Ankle Circles',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'bodyweight',
    id: '62609c9e-f641-5e91-a41a-c78433485993',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Donkey Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'bodyweight',
    id: 'd18231aa-3c0a-5ce7-9449-cc77d57e6627',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Donkey Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'bodyweight',
    id: '438a4c04-7aaf-548c-8710-c1a687b694f0',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Chest Dip',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'bodyweight',
    id: '105604e1-056c-5255-ade3-fbf840c48b34',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Clock Push-up',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'bodyweight',
    id: 'de12ac89-725a-5583-80cf-0c83e1fbf0e3',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Drop Push Up',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'bodyweight',
    id: 'cece20de-7976-5796-babd-585fc4339c43',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Straight Bar Dip',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'bodyweight',
    id: 'c0a4a339-bf63-5414-a209-80047a225351',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Svend Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'bodyweight',
    id: 'e97b14dd-4b36-53b1-9d20-5eddb4b9d0c3',
    loggingMode: 'duration',
    name: 'Bodyweight Incline Side Plank',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '6c0be6d7-bb31-5734-9cc4-f2c7b57480a3',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Curl-up',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '76820c21-b515-550f-88d7-b78b462ce3c8',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Elbow-to-knee',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '2b479243-e753-530d-bf43-36426d69de4b',
    loggingMode: 'duration',
    name: 'Front Plank With Twist',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: 'e7289a2a-1407-5c85-82b7-e246e6f14aff',
    loggingMode: 'duration',
    name: 'L-sit On Floor',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '437d0752-d478-5d65-9989-6cebf4ff089a',
    loggingMode: 'duration',
    name: 'Power Point Plank',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '64391ebd-c949-575b-9816-1f0c808a1820',
    loggingMode: 'duration',
    name: 'Push-up To Side Plank',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: 'a242459c-92fd-535f-8932-da5f374a17f1',
    loggingMode: 'duration',
    name: 'Reverse Plank With Leg Lift',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '3971b5d6-4fb6-526e-bc26-3156d67bbe96',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Crunch',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: 'd2c2d896-a158-50f9-ae0c-b6fd97f48fa6',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Decline Sit-up',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '37333ae0-e819-5bc7-b17a-b796f42aed6a',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Front Plank',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '73d02381-41b0-5fd1-8e4f-cb731596e295',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Hanging Leg-hip Raise',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '624035bc-8f45-5aad-aeff-dc8a20305fb5',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Russian Twist',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'bodyweight',
    id: '630009cf-7b80-5f73-9d43-b0c2bd8a9f3f',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Curtsey Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'bodyweight',
    id: '2c9d4cfb-f86c-5d3e-b027-c0082dd214be',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Lunge With Swing',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'bodyweight',
    id: '34db068b-02f1-5068-ad42-d0d7cc797ac1',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'bodyweight',
    id: '8f79c4f8-3336-537e-a16b-49baa680e8e5',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Glute-ham Raise',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'bodyweight',
    id: 'd2c097a8-759f-565e-ab6d-a3035841feb8',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Backward Jump',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'bodyweight',
    id: '69c12ac3-75fa-58a2-b0c7-65139aba1132',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Sissy Squat',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'bodyweight',
    id: '398242bb-ed1e-5dd2-9677-7e2e06c4c41b',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Front Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'bodyweight',
    id: '0482c97c-9520-54f7-b9ac-59f90fd23535',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Kneeling Step With Swing',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'bodyweight',
    id: '0c0a247d-965d-5fc9-9d8d-7b9d7d4bd5b2',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Round Arm',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'bodyweight',
    id: 'ddde6de2-f8e4-546d-afa3-03536eda0ddb',
    loggingMode: 'bodyweight-and-repetitions',
    name: 'Handstand',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'bodyweight',
    id: '2d6bb671-5746-51e2-a316-580df1bde0c2',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Bench Dip',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'bodyweight',
    id: 'f7e96175-b7d9-5910-8e83-d02628cfdd6b',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Three Bench Dips',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'bodyweight',
    id: '352bd73d-9160-51eb-b52b-ffb474767d7a',
    loggingMode: 'bodyweight-plus-load-and-repetitions',
    name: 'Weighted Tricep Dips',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'cable',
    id: '97c2a616-d389-54c3-a188-1795b7a16268',
    loggingMode: 'external-load-and-repetitions',
    name: 'Alternate Lateral Pulldown',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'cable',
    id: '656cc1ee-6dd8-5092-b7a5-edcfda87e6a3',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Pulldown',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'cable',
    id: '5e97801e-56c8-5d78-b571-5a85f6ff9827',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'cable',
    id: '1ce1187e-dda0-51c3-8aa0-5c3c1315160c',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Concentration Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'cable',
    id: '72ea18cd-2a56-582b-96ff-9f3a5b7e8a26',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'cable',
    id: 'bf51d79d-cb0d-5d5e-b036-fdbf0098d9ed',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Standing Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'cable',
    id: 'd34d0c1d-95cf-5346-b5eb-ee69f001ca86',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Standing One Leg Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'cable',
    id: 'd4f79ef8-50e6-5116-9b5b-4db31da2d4ae',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Bench Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'cable',
    id: '56356049-7a1a-58f0-b3f0-5fedcc6813a1',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Cross-over Variation',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'cable',
    id: '8576a4bd-13ad-58d6-b360-5d50b74f156e',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Judo Flip',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'cable',
    id: 'e3af033e-9966-5975-9b7e-b806e52b8df9',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Twist',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'cable',
    id: 'b4876de2-e042-5eda-a26d-358d5ddb6a92',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Deadlift',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'cable',
    id: '521a3da4-8564-5950-ab3a-2e61f621b02d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Standing Hip Extension',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'cable',
    id: 'a7e2a69f-ba51-524a-8ec7-46ddbd2def18',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Assisted Inverse Leg Curl',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'cable',
    id: 'ab88b36a-1052-5a47-95af-88c70293aca7',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Forward Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'cable',
    id: '0600bc0a-e8cd-5c6d-b3ef-7019f9c88aaa',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Front Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'cable',
    id: '3f80c6f3-eddc-59c4-87f5-d4990e481f4b',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Lateral Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'cable',
    id: 'd4654c0d-61d3-5edc-acb7-5f122900fff5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Kickback',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'cable',
    id: '0b9efdd6-c422-5bc3-8f76-deb9e1f5220f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Pushdown',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'cable',
    id: 'e27ae78b-28f8-50b5-99d5-a3afa5c5c30c',
    loggingMode: 'external-load-and-repetitions',
    name: 'Cable Rear Drive',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'cardio-machine',
    id: '92783b2b-c6b3-5247-b70b-33822f5f979e',
    loggingMode: 'distance',
    name: 'Cycle Cross Trainer',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: '23bf34d2-025c-5ad1-a21e-0dcd07314be8',
    loggingMode: 'distance',
    name: 'Hands Bike',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: '7f1d4d87-b419-5496-8221-2e4d0fc52734',
    loggingMode: 'distance',
    name: 'Ski Ergometer',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: '94ca5089-5de5-58c2-bd56-d07aa1d29d58',
    loggingMode: 'distance',
    name: 'Stationary Bike Run',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: 'ef153153-5d3e-5f6b-952f-77c67e5d2164',
    loggingMode: 'distance',
    name: 'Stationary Bike Walk',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: 'c77f9f0e-ffc8-5ea2-b1af-07297010fd3b',
    loggingMode: 'distance',
    name: 'Walk Elliptical Cross Trainer',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: 'c42502af-65f0-5777-b320-15d580eb85d4',
    loggingMode: 'distance',
    name: 'Walking On Incline Treadmill',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'cardio-machine',
    id: '90f20f27-bee9-53e9-95df-e3e4980088f8',
    loggingMode: 'distance',
    name: 'Walking On Stepmill',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'dumbbell',
    id: '609b5f5f-16d0-5904-8de4-6d86a9e2eae9',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Decline Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'dumbbell',
    id: '5c87301e-1c62-5a0e-8a27-43fcd2315290',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Incline Row',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'dumbbell',
    id: '5b11c00f-35b3-52e5-8133-148a25c94ac5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Incline Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'dumbbell',
    id: '3378ee59-e57f-5030-a964-15f41e7148b1',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'dumbbell',
    id: '1c3705f6-fcf1-5f71-a4ec-dcd62a174f6a',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Concentration Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'dumbbell',
    id: 'ecfd6907-a392-546b-a8ab-ff29bd5ef32f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Hammer Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'dumbbell',
    id: 'eaa925fa-82cb-54f6-9a41-884f5432525d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell High Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'dumbbell',
    id: '604d446f-e506-52af-a76c-c009add6b91a',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Incline Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'dumbbell',
    id: '866c81f6-9c55-5ed2-8f2c-0bbf5e9935ee',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Seated Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'dumbbell',
    id: '2b957bd2-c161-52b9-b0ae-a1e02cd98b8a',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Seated One Leg Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'dumbbell',
    id: '47234d18-a7c1-5dff-8d4a-a4bc3692d4cf',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Single Leg Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'dumbbell',
    id: 'ad9c39c6-7410-55d9-bdce-593dda7a5eaa',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Standing Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'dumbbell',
    id: 'fcb6fe50-4034-5fc4-9a15-5cc9e980658c',
    loggingMode: 'external-load-and-repetitions',
    name: 'Deep Push Up',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'dumbbell',
    id: 'a76c420a-1910-50eb-9d48-7ea13ee247c5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Around Pullover',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'dumbbell',
    id: '88aeb33b-f488-5a78-99e7-98890c6b7409',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Fly',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'dumbbell',
    id: '15006518-13d2-51aa-a868-bd87e91c61b8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Pullover',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'dumbbell',
    id: '2b788887-5b40-5178-9841-16380977e1c4',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Side Bend',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'dumbbell',
    id: '28d08b15-32ed-5229-9ce3-aa3350152766',
    loggingMode: 'external-load-and-repetitions',
    name: 'Spell Caster',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'dumbbell',
    id: 'bd88c663-1cc1-52e1-b188-2c8dbe97cacd',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Clean',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'dumbbell',
    id: '202dabef-b74d-5c31-a204-bd2a16e4d882',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Deadlift',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'dumbbell',
    id: '8f262806-c913-521e-8dc1-0a019dde11e8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Lunge',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'dumbbell',
    id: '34ff7e9a-3f51-5d03-8e9f-a3d61a9d4aa5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'dumbbell',
    id: '25fa368f-6ee2-50cf-bb8f-8e122bf4d99f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Lying Femoral',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'dumbbell',
    id: '40f144d1-abf1-5be4-8adc-3e89e55e026d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Goblet Squat',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'dumbbell',
    id: 'd201f457-5c7f-5f1e-8aac-20b8a5970f69',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Step-up Lunge',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'dumbbell',
    id: '08f7b8f6-1607-565c-a529-a0476d9fca7a',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Supported Squat',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'dumbbell',
    id: '2b9947d0-532d-5f83-8634-a5e83e59b668',
    loggingMode: 'external-load-and-repetitions',
    name: "Farmer's Walk",
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'dumbbell',
    id: '9fa23e60-bcfe-579a-9f74-404abd6f0190',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Arnold Press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'dumbbell',
    id: '60934f55-790c-50ef-a510-e2c43b947712',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Cuban Press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'dumbbell',
    id: '7b1a8171-51ac-5cab-87f9-681f0aa3dcb5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'dumbbell',
    id: 'f8cc098b-bb90-5b61-8302-a5acd9a20438',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell W-press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'dumbbell',
    id: '4cdb9d53-9364-504f-a2d6-6c64f869ff25',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Close-grip Press',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'dumbbell',
    id: 'bdae0c8a-d1e5-5514-92fb-d33a6456048f',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Kickback',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'dumbbell',
    id: '2d5258da-002b-516f-bb8b-d799ef64c0ed',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Seated Kickback',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'dumbbell',
    id: 'b5f97667-02aa-5be8-bfcc-39c6963b8f81',
    loggingMode: 'external-load-and-repetitions',
    name: 'Dumbbell Standing Kickback',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'kettlebell',
    id: 'b43702ca-1ff3-58ef-b2ee-113f5303df41',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Alternating Renegade Row',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'kettlebell',
    id: '4f246801-b2a1-5631-98f6-8bcca2c08309',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Alternating Row',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'kettlebell',
    id: '697ef3f6-fd3d-50ca-82cb-7b3318a60e9d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Double Alternating Hang Clean',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'kettlebell',
    id: '243ea7bf-7ce1-568d-97b4-b3cb4f869190',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Alternating Press On Floor',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'kettlebell',
    id: '07244b83-df5d-5582-9b97-4a3d72f1d9b3',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell One Arm Floor Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'kettlebell',
    id: 'ff72332d-19a7-506b-a136-9d30d2ea75c8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Plyo Push-up',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'kettlebell',
    id: '95dfc32a-bc9a-5994-8a84-6555942a68af',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Advanced Windmill',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'kettlebell',
    id: 'ec4a04e4-ec12-537d-be8f-d11244cd48bb',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Bent Press',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'kettlebell',
    id: 'a2a7645b-31e3-5be7-9722-9f0cfd700e64',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Windmill',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'kettlebell',
    id: 'b43293bd-8286-5d4a-9f7f-42bed289df74',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Front Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'kettlebell',
    id: '8c7f19e9-0d08-54b8-89bf-b45144224beb',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Goblet Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'kettlebell',
    id: 'd56e749f-ea15-50b2-b2d7-84ea129bc998',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Hang Clean',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'kettlebell',
    id: '80dc7021-9d10-5ffc-b83a-334b089c1444',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Alternating Press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'kettlebell',
    id: '212c8169-cb3f-5cf5-9ae1-56b04ac0ee7e',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Arnold Press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'kettlebell',
    id: 'cc71b43d-180d-5adf-9bd4-8960ebf9f561',
    loggingMode: 'external-load-and-repetitions',
    name: 'Kettlebell Thruster',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'machine',
    id: 'c57ad601-93cb-50ba-8f21-9ed2df947637',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Pullover',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'machine',
    id: 'b77e391e-c07f-5b6f-b898-e3b2525929b4',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'machine',
    id: 'c09b0e16-905c-52dc-b8d2-7b8a07156139',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Bicep Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'machine',
    id: 'dd688c27-fb08-51b9-ad2b-a009b49de83d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Preacher Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'machine',
    id: '0464617b-041e-51c5-abb9-55f5f0661111',
    loggingMode: 'external-load-and-repetitions',
    name: 'Hack Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'machine',
    id: '798923d1-328b-51a9-92b3-b40e2295e591',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Calf Press',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'machine',
    id: 'a2c96d94-fbe8-50e6-9655-681390acbe36',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Chest Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'machine',
    id: 'e2084dc7-b739-5e04-be39-8b849d31d1dd',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Seated Fly',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'machine',
    id: '4e964105-5fbf-55e5-9c84-aa90f00dedb7',
    loggingMode: 'assistance-and-repetitions',
    name: 'Assisted Hanging Knee Raise',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'machine',
    id: '0a05b875-15d2-5049-b2bf-845254402cf8',
    loggingMode: 'assistance-and-repetitions',
    name: 'Assisted Sit-up',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'machine',
    id: 'd04e6527-8919-50dd-aec2-3fd324820d32',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Kneeling Twist',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'machine',
    id: '3fdfc77d-a1e2-5b5a-b1a3-419b02fe59d8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Seated Crunch',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'machine',
    id: 'e8916560-c728-5ce9-a162-59e9aa8ba7d8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Deadlift',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'machine',
    id: 'f62c1dda-9ac8-59ab-93c0-4738f3e8b6a1',
    loggingMode: 'external-load-and-repetitions',
    name: 'Smith Deadlift',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'machine',
    id: '5fa54452-ba3c-567a-9051-3d9268248507',
    loggingMode: 'assistance-and-repetitions',
    name: 'Assisted Prone Hamstring',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'machine',
    id: 'cf84eeab-1e01-589d-ab9f-96a6e9a311fc',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Kneeling Leg Curl',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'machine',
    id: '2bfb67f0-a0c4-592c-8622-6373b9ffe7e6',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Lying Leg Curl',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    equipment: 'machine',
    id: '532b2c94-f577-5f3e-b890-4f0b56ac03d9',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Leg Extension',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'machine',
    id: '764d9ee3-440c-56a2-9ec2-45204fcf979d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Smith Chair Squat',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'machine',
    id: 'b7ceb09d-8654-5860-84ab-4109e2fd4dbc',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Lateral Raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'machine',
    id: '63053fa8-1696-5a2c-a7b0-45b673c03a00',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Military Press',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'machine',
    id: '32f21fd1-7a3e-5d05-a658-df618c5ee6ad',
    loggingMode: 'external-load-and-repetitions',
    name: 'Lever Seated Dip',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'none',
    id: 'a59dd4dc-e429-50bc-829f-a72810318cfd',
    loggingMode: 'repetitions',
    name: 'Back And Forth Step',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: 'c974f204-25c5-53ca-8e58-91290fa0fa8d',
    loggingMode: 'repetitions',
    name: 'Bear Crawl',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: 'fbfe194e-c104-554b-8fff-6c0f74f777f9',
    loggingMode: 'repetitions',
    name: 'Dumbbell Burpee',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: 'efbe01db-a4ca-5987-b751-211f122ccda3',
    loggingMode: 'repetitions',
    name: 'High Knee Against Wall',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: '4fbef62f-8187-57c9-9f49-4328cb66d1eb',
    loggingMode: 'repetitions',
    name: 'Jack Burpee',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: 'b65eba80-23e8-55a7-8c21-7a6e51364207',
    loggingMode: 'repetitions',
    name: 'Mountain Climber',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: '295d944e-2f2c-555a-a929-75e9c7e5073a',
    loggingMode: 'repetitions',
    name: 'Short Stride Run',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: 'a49fe3a6-5fe5-5197-a968-ed2ae9200735',
    loggingMode: 'repetitions',
    name: 'Skater Hops',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'none',
    id: '1211391c-5f57-5914-8b09-ae14cfce8b47',
    loggingMode: 'repetitions',
    name: 'Walking High Knees Lunge',
    primaryMuscleGroup: 'conditioning',
  },
  {
    equipment: 'resistance-band',
    id: '5848bc08-5e78-527e-9a06-25cb26f0f051',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Assisted Pull-up',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'resistance-band',
    id: 'f1841482-db5b-50fb-b71d-f8cbc59b977a',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Shrug',
    primaryMuscleGroup: 'back',
  },
  {
    equipment: 'resistance-band',
    id: 'fecc714e-92aa-577c-ae81-2d31ab7447f8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Alternating Biceps Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'resistance-band',
    id: '6daf8e77-8296-55d9-b034-7b150b49062e',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Concentration Curl',
    primaryMuscleGroup: 'biceps',
  },
  {
    equipment: 'resistance-band',
    id: 'fcb2beaa-6740-5493-a6b2-0df4c2416438',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Single Leg Calf Raise',
    primaryMuscleGroup: 'calves',
  },
  {
    equipment: 'resistance-band',
    id: '05bb6aa7-82de-51e7-881c-955b5c420f55',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Bench Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'resistance-band',
    id: '4c5aa5d9-8c67-50cf-adc5-d5e71426235d',
    loggingMode: 'external-load-and-repetitions',
    name: 'Resistance Band Seated Chest Press',
    primaryMuscleGroup: 'chest',
  },
  {
    equipment: 'resistance-band',
    id: '7e8b82e5-33d4-5f26-860a-93bb87f79d05',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Alternating V-up',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'resistance-band',
    id: '5359969b-15e4-55bc-960f-7bf95e7f98a8',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band V-up',
    primaryMuscleGroup: 'core',
  },
  {
    equipment: 'resistance-band',
    id: '35a1f0a7-799a-55b8-83ab-b4aa3d03b45c',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Squat',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'resistance-band',
    id: '2bd6b1dd-05eb-5aa7-884f-0d9c9f7147c5',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Step-up',
    primaryMuscleGroup: 'glutes',
  },
  {
    equipment: 'resistance-band',
    id: '0050bce5-8ad1-5d47-a94c-eca55adecf74',
    loggingMode: 'external-load-and-repetitions',
    name: 'Resistance Band Leg Extension',
    primaryMuscleGroup: 'quadriceps',
  },
  {
    equipment: 'resistance-band',
    id: '1204cb86-1d0d-5d04-8238-37502e87bd65',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Y-raise',
    primaryMuscleGroup: 'shoulders',
  },
  {
    equipment: 'resistance-band',
    id: '54eff46c-1a67-5211-9220-c91f8a7e7165',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Close-grip Push-up',
    primaryMuscleGroup: 'triceps',
  },
  {
    equipment: 'resistance-band',
    id: '71bf4137-2859-5caf-96ec-d2edec2abdc9',
    loggingMode: 'external-load-and-repetitions',
    name: 'Band Side Triceps Extension',
    primaryMuscleGroup: 'triceps',
  },
] as const satisfies readonly StarterExercise[]);

/**
 * Stated once so the interface, the result sentences, and the tests all
 * count the same set, and so a content change that forgets one of them
 * fails loudly.
 */
export const expandedExerciseCount = expandedExercises.length;
